### ISSUE TITLE
Criar máscara para o campo "Nome do arquivo" em "Cadastro de propriedade"

### ISSUE THREAD

**Issue by jrlamb** [jrlamb/SNAC#29]
O campo "nome do arquivo" deve sugerir o nome do arquivo a ser adicionado ou então facilitar a localização do arquivo junto ao diretório \assets. 

Lembrar que o usuário não tem nem ideia de como esse arquivo é adicionado.

**Comment by jrlamb** [comment]
Lembrando que o usuário deve fazer o UPLOAD do arquivo.

**Comment by jrlamb** [comment]
Lembrando que o usuário deve fazer o UPLOAD do arquivo.

**Comment by sganderla** [comment]
Professor, acho que não precisa fazer upload
pq vc está dentro próprio aparelho... O mecanismo fico assim...

Criei uma pasta do projeto em um lugar publico do aparelho. O usuário coloca os arquivos dentro da pasta e quando for cadastra uma propriedade vc seleciona um arquivo da pasta

**Comment by jrlamb** [comment]
Entendi. Só é necessário acrescentar diversas mensagens alertando o usuário disso. Issue re-opened para adicionar as mensagens assim como feito nas outras issues, pode ser?

**Comment by jrlamb** [comment]
Não foi possível testar essa funcionalidade

**Comment by sganderla** [comment]
Funcionalidade deve estar disponível no ultimo commit
