### ISSUE TITLE
Vincular o "Cadastro de propriedade" com a listagem de propriedade em "Navegar"

### ISSUE THREAD

**Issue by jrlamb** [jrlamb/SNAC#31]
As propriedades cadastradas não tem nenhum vínculo com o módulo de navegação. Cadastrei uma nova propriedade e, não apareceu-a na lista para navegação.

**Comment by jrlamb** [comment]
Testei hoje 02/05 e continua o mesmo problema, não existindo vínculo entre cadastro de propriedade e lista de propriedades em navegar.

**Comment by sganderla** [comment]
Funcionalidade ainda não finalizada.
