### ISSUE TITLE
Criar/Destacar/Evidenciar o modo para retornar a um ponto cadastrado

### ISSUE THREAD

**Issue by jrlamb** [jrlamb/SNAC#32]
Encontrei a opção para cadastro do ponto, aparentemente está funcionando corretamente. Quanto a opção para retornar ao ponto cadastrado fiquei em dúvida se é clicando nela ou então, não está implementada. 

O comportamento padrão é, ao clicar no ponto, entrar em edição. 
Para retornar ao ponto, criar outro menu.

**Comment by sganderla** [comment]
Na lista de pontos tem 2 datas uma de cadastro e outra de retorno. Para retornar a um ponto, basta selecionar o ponto, que o sistema marcará o ponto de origem e o ponto de destino. 

Caso não tenha sinal de GPS é para abrir o mapa normalmente, mas aparece uma mensagem informando que o GPS está inativo. Para cadastrar um ponto, sem GPS basta clicar sobre o mapa.
