### ISSUE TITLE
Falha em "Cadastrar ponto"

### ISSUE THREAD

**Issue by jrlamb** [jrlamb/SNAC#37]
Ao abrir a janela de cadastro do ponto, o mapa é exibido, mas eu não sou localizado no mapa. O ponto a ser cadastrado deve corresponder à posição atual do equipamento.

O ponto não é selecionado, deve corresponder a localização atual do celular.
Exibir ainda nessa janela, o raio com a margem de erro de localização e valor em metros (do erro de localização)

**Comment by sganderla** [comment]
Exibir ainda nessa janela, o raio com a margem de erro de localização e valor em metros (do erro de localização) (Não entendi)
