### ISSUE TITLE
Falha em atualizar ponto

### ISSUE THREAD

**Issue by jrlamb** [jrlamb/SNAC#39]
Ao selecionar a opção de atualizar um ponto já cadastrada, deve ser exibido o ponto antigo e a nova localização. 

Deve-se usar cores como vermelha para o velho, e verde para o novo (coordenada atual). Ou então legenda para o usuário visualizar claramente a distinção entre as duas posições.

**Comment by sganderla** [comment]
Estou trabalhando com o ponto padrão azul como ponto atual e o ponto vermelho o ponto cadastrado

**Comment by jrlamb** [comment]
Ao atualizar um registro, coloque uma mensagem "Tem certeza de que deseja alterar o registro selecionado?". Isso vale para todos os cadastros;

**Comment by sganderla** [comment]
Juliano está mensagem seria antes de abri a seleção? ou antes de salvar a alteração?

**Comment by sganderla** [comment]
vou colocar antes de abri a edição.
