### ISSUE TITLE
Arquivos de pontos XML não são salvos em /SNAC

### ISSUE THREAD

**Issue by jrlamb** [jrlamb/SNAC#43]
Ao cadastrar uma nova propriedade, o arquivo de pontos desta, não é salvo em SNAC. 

A propriedade é cadastrada e o arquivo de pontos continua apontando para o caminho original dele ao invés de ser copiado para o diretorio /SNAC.

Dessa maneira - atualmente - a pasta /SNAC não serve para nada no projeto.

**Comment by sganderla** [comment]
Ao cadastrar uma nova propriedade, o arquivo de pontos desta, não é salvo em SNAC.
Ele não vai fica salvo no SNAC mesmo. Ele fica onde o usuário referenciou ele. Pq não faz sentido fazer a cópia e ter dois arquivos iguais, ou ate mesmo trocar a referência que o usuário fez que ele saiba.

**Comment by jrlamb** [comment]
Nao pode set mantido a referência original pois podemos ter 10 propriedades e 10 caminhos diferentes.  Ao indicar o arquivo,  este deve ser copiado para /snac e mantendo referência a esse caminho.

**Comment by sganderla** [comment]
Está copiando o arquivo para dentro da pasta do SNAC... (Obs = Tenho que verificar  a permissão da pasta e dos arquivos)
