### ISSUE TITLE
Alterar rotulos do nível de importância

### ISSUE THREAD

**Issue by jrlamb** [jrlamb/SNAC#45]
Alterar os rotulos do chamado nível de importância, no cadastro de pontos.

De "Nível de importância" para "Tipo de fenômeno"
Opções:
- Praga (insetos e outros invasores)
- Erva daninha/invasora
- Doença 
- Outros

Deixar esses rótulos passíveis de alteração junto ao arquivo de strings.

**Comment by sganderla** [comment]
Teria um cadastro de Tipo de Fenômeno então?

**Comment by sganderla** [comment]
Issues Finalizada
