### ISSUE TITLE
Não é possível atualizar a coordenada geografica de um determinado ponto

### ISSUE THREAD

**Issue by jrlamb** [jrlamb/SNAC#46]
Não é possível atualizar a coordenada de um ponto cadastrado. Podem ser alteradas as demais informações, mas não é possível atualizar um ponto cadastrado. Por que não?

**Comment by sganderla** [comment]
Atualmente na edição, não esta atualizando o ponto pela a localização atual, porem permite editar pelo click no mapa. Isso basta?

**Comment by jrlamb** [comment]
Nao.  Pois o cadastro parte da localização.  A atualização também deve ser feita por meio da posição atual.
